### ISSUE TITLE
Week 01 回饋

### ISSUE THREAD

**Issue by azole** [rachelwu-wu/git-practice#1]
我也覺得 ChatGPT 是一把雙面刃，他可能會拉開「主動思考」跟「不會主動思考」的人的差距，這個差距原本就一直在，但有了 ChatGPT 後，會更嚴重。

git 這份作業，經過上週課程的討論，如果你有去看分享出來的、做得不錯的作業，應該有感受到自己做得不夠深入，整體正確，但不夠深入，如上課時所言，讓自己對技術也更多的好奇心。特別你有提到，你之前不是資管系的畢業生，我對於非相關科系要轉職來成為工程師這件事的看法跟其他人不同，我反而覺得這樣是加分的，雙專業耶，應該要加上很多分啊？但這個前提是，要學好、要學扎實，也確實，這過程，會非常非常地辛苦，希望你有這個心理準備，不要給自己找理由，讓我們扎實地度過這學習，成為一名合格的軟體工程師。

**Comment by azole** [comment]
這個 issue 如果沒有需要討論的地方，就可以先 close 嚕！

**Comment by rachelwu-wu** [comment]
其實我真的很喜歡老師柔順且耐心的跟我們一對一的討論問題，雖然還是會因為被老師很一針見血的點出問題而緊張，但我覺得是很快可以練功的方法，會繼續加油，也請老師跟自己都多多指教了～～我close嚕！
